import { readWorkerConfig, type CompiledExecutionTarget, type WorkerConfig } from "@modules/config";
import pc from "picocolors";
import { exitWithError, UI } from "./ui";

function countCompiledTargets(config: WorkerConfig): number {
  return (config.rules ?? []).reduce((count, rule) => count + rule.targets.length, 0);
}

function countCompiledPiiColumns(config: WorkerConfig): number {
  return (config.rules ?? []).reduce(
    (count, rule) => count + rule.targets.reduce((targetCount, target) => targetCount + target.pii_columns.length, 0),
    0
  );
}

function renderTarget(target: CompiledExecutionTarget): string {
  const pii = target.pii_columns.length > 0 ? target.pii_columns.join(", ") : "none";
  const action = target.action ?? "none";
  return `${target.table} | action=${action} | pii=${pii}`;
}

/**
 * Inspects a worker manifest without connecting to the database.
 *
 * The command is intentionally read-only. It validates YAML shape, resolves local key material using
 * placeholder keys when needed, and prints the legal/configuration coverage developers must review
 * before running `check-integrity` against a live database.
 *
 * @param options - CLI options containing the manifest path.
 * @returns Resolves after printing the manifest summary.
 */
export async function inspectAction(options: { config: string }): Promise<void> {
  UI.header("Manifest Inspection");

  const mockEnv = {
    ...process.env,
    DPDP_MASTER_KEY: process.env.DPDP_MASTER_KEY || "0".repeat(64),
    DPDP_HMAC_KEY: process.env.DPDP_HMAC_KEY || "0".repeat(64),
  };

  let config: WorkerConfig;
  try {
    config = await readWorkerConfig(mockEnv, options.config);
  } catch (error) {
    exitWithError("Manifest inspection failed", error instanceof Error ? error.message : String(error));
  }

  UI.step(1, "Legal Attestation");
  UI.keyValue("DPO", config.legal_attestation.dpo_identifier);
  UI.keyValue("Version", config.legal_attestation.configuration_version);
  UI.keyValue("Review Date", config.legal_attestation.legal_review_date);
  UI.keyValue("Schema Hash", config.legal_attestation.schema_hash ?? config.integrity.expected_schema_hash);
  UI.keyValue("Generated By", config.legal_attestation.generated_by ?? "manual");

  UI.step(2, "Database Boundary");
  UI.keyValue("App Schema", config.database.app_schema);
  UI.keyValue("Engine Schema", config.database.engine_schema);
  UI.keyValue("Root Table", config.graph.root_table);
  UI.keyValue("Root ID Column", config.graph.root_id_column);
  UI.keyValue("Root PII Columns", Object.keys(config.graph.root_pii_columns).join(", "));

  UI.step(3, "Execution Coverage");
  UI.keyValue("Compiled Rules", String((config.rules ?? []).length));
  UI.keyValue("Compiled Targets", String(countCompiledTargets(config)));
  UI.keyValue("Compiled PII Columns", String(countCompiledPiiColumns(config)));
  UI.keyValue("Satellite Targets", String(config.satellite_targets.length));
  UI.keyValue("Blob Targets", String(config.blob_targets.length));
  UI.keyValue("Retention Rules", String(config.compliance_policy.retention_rules.length));

  if ((config.rules ?? []).length === 0) {
    UI.warn("No compiled DAG rules found. Run compliance-worker introspect and review the generated targets.");
  } else {
    const table = UI.table(["Rule", "Target"]);
    for (const rule of config.rules ?? []) {
      for (const target of rule.targets) {
        table.push([pc.bold(rule.id), renderTarget(target)]);
      }
    }
    console.log(table.toString());
  }

  UI.step(4, "Next Checks");
  UI.subStep("Run compliance-worker check-integrity --config <path> against the target database.");
  UI.subStep("Run compliance-worker sign --config <path> after DPO approval.");
  UI.subStep("Deploy only signed manifests with matching schema hashes.");
}
