import { formatQualifiedTable, yamlScalar } from "./naming";
import type { IntrospectorDraft, IntrospectorTargetDraft, PotentialLogicalLink } from "./types";

function formatNumber(value: number): string {
  return Number.isInteger(value) ? value.toFixed(1) : value.toFixed(3);
}

function renderPiiColumns(target: IntrospectorTargetDraft): string {
  if (target.piiColumns.length === 0) {
    return "[]";
  }

  return `[${target.piiColumns.map((column) => yamlScalar(column.column)).join(", ")}]`;
}

function renderTarget(target: IntrospectorTargetDraft): string[] {
  const lines = [
    `      - table: ${yamlScalar(formatQualifiedTable(target.table))}`,
  ];

  if (target.parentTable) {
    lines.push(
      `        parent: ${yamlScalar(formatQualifiedTable(target.parentTable))}`,
      `        join: ${JSON.stringify(target.fkCondition)}`,
      `        parent_columns: [${target.parentColumns.map((column) => yamlScalar(column)).join(", ")}]`,
      `        child_columns: [${target.childColumns.map((column) => yamlScalar(column)).join(", ")}]`
    );
  }

  for (const column of target.piiColumns) {
    lines.push(
      `        # Introspector Confidence: ${formatNumber(column.confidence)} (${column.matchedSignatures.join(", ") || "metadata"})`
    );
  }

  lines.push(`        pii_columns: ${renderPiiColumns(target)}`);
  if (target.parentTable && target.piiColumns.length > 0) {
    lines.push("        primary_key_columns: [id]");
  }
  if (target.parentTable && target.piiColumns.length > 0) {
    lines.push(
      "        action: redact",
      "        mutation_rules:"
    );
    for (const column of target.piiColumns) {
      lines.push(`          ${yamlScalar(column.column)}: HMAC`);
    }
  }
  return lines;
}

function renderLogicalLinks(links: readonly PotentialLogicalLink[]): string[] {
  if (links.length === 0) {
    return ["# Potential Logical Links: none detected"];
  }

  return links.map(
    (link) =>
      `# [Potential Logical Link] ${formatQualifiedTable(link.sourceTable)}.${link.column} <-> ${formatQualifiedTable(link.targetTable)}.${link.column} - ${link.reason}`
  );
}

/**
 * Renders a deterministic YAML draft without depending on a YAML serializer.
 *
 * @param draft - Compiled DAG and classified PII targets.
 * @returns `compliance.worker.yml.draft` content for DPO review.
 */
export function renderIntrospectorYaml(draft: IntrospectorDraft): string {
  const lines = [
    "# AUTO-GENERATED BY AVANTII INTROSPECTOR",
    "# REVIEW REQUIRED: DPO must validate every table, join condition, and PII column before production use.",
    `# Generated At: ${draft.generatedAt}`,
    "",
    "legal_attestation:",
    "  dpo_identifier: PENDING_REVIEW",
    "  configuration_version: introspector-draft",
    "  legal_review_date: PENDING_REVIEW",
    `  schema_hash: ${draft.schemaHash}`,
    "  generated_by: avantii-introspector-v1",
    "  acknowledgment: PENDING_REVIEW",
    "",
    "legal_disclaimer:",
    "  text: \"Auto-generated by Avantii. The DPO/Developer is responsible for verifying all logical links and PII mappings.\"",
    "",
    "rules:",
    "  - id: dpdp_standard",
    `    root_table: ${yamlScalar(formatQualifiedTable(draft.root))}`,
    `    max_depth: ${draft.maxDepth}`,
    "    targets:",
  ];

  for (const target of draft.targets) {
    lines.push(...renderTarget(target));
  }

  lines.push("", ...renderLogicalLinks(draft.potentialLogicalLinks));
  lines.push("");
  return `${lines.join("\n")}`;
}

